sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fRpK8VWp7uz/e6Q2WLN1wgazV6n2d3MDIEu3Hgwa/o30gIkf0Ol3XXNOWJrc3+eR3Jab2eqy55HCSefgmCIYWuvVTmUr1duwdy6pBTZYOHkCNzPGdQhqEhlfouqZjjxj3/kdNJIiXuxyaJJDK46cE3+jeolFpN0RGmh7ofwxM/hNH8pkCKFTQGDuPe8XzuX4CevyVh5ioeAeSXRl+Yng86hqfPQkoGvPoc4hcpZ+FjQBFu6WGzrlrVkDhVQ8qEhlk/Dr79LnrhIb9d5ziogDDwOl9apPFc1N5CmfzUhWFIMdNnCrCocyrFJMo0JJZCzuAVbRNLyTXA4Y0KwR2hp9DHXRmttmEDJHcL237vIepYue2gMpIZ0pFhISo6Q03uJ+ClGAIut2oH6GvkSjgAn0Fn/dgdfg5R+ML3dmJE8l6pgaLO0aFJIdxPXN5Ly8KqD/XcV63yuYvfntzgpaYO4FphLrZcRwa1P/COMbMYen5Au6IRo1pJC+0jYXOmsdHjOftRWUtwSJEct5TFUaK3Pvr/PNSw1bVDR4O3nMqtQlIeidEN6Sozwt2OSzk4PNYgKnbiKQ0pQPQeug/V3T3S6gVm8o9vFJ1DFliz9mtCzCVEm2qO7W4pvGuFuinBlFYw3CUCcWBDdCmxO+ehGhel7s/e2dQypwig/Bymkk1cvC31Q=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Tom-Swift-in-the-Land-of-Wonders--Or-The-Underground-Search-for-the-Idol-of-Gold_499
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy